AWSTemplateFormatVersion: "2010-09-09"
Description: Template to build lambdas and dependencies for lambdas

Parameters:

  SourceLocation:
    Type: String
    Description: S3 bucket path where the original source code (and cfn config) is stored

  MarketdataDownloaderDeleteTestFilesKey:
    Type: String
    Description: S3 key where the built delete lambda is stored

  Name:
    Type: String
    Description: Name of the stack

Resources:

  LambdaRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyName: LambdaRequired
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: LambdaPolicy
                Action:
                  - 's3:*'
                  - 'sns:*'
                  - 'lambda:*'
                  - 'athena:*'
                  - 'glue:*'
                Effect: Allow
                Resource: '*'
              - Sid: CloudWatchWriteLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  MarketdataDownloaderCleanTestFilesLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'MarketdataDownloaderArtifactsBucket'
        S3Key: !Ref MarketdataDownloaderDeleteTestFilesKey
      FunctionName:
        Fn::Sub: market_data_downloader_clean_test_files
      Handler: "market_data_downloader_clean_test_files.lambda_handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
      Timeout: 300

  MarketdataDownloaderCleanTestFiles:
    Type: Custom::DeleteTestFiles
    DependsOn:
      - MarketdataDownloaderCleanTestFilesLambda
    Properties:
      ServiceToken: !GetAtt 'MarketdataDownloaderCleanTestFilesLambda.Arn'
      BucketName: market-data-downloader-test-market-data-downloader

Outputs:

  MarketdataDownloaderCleanTestFilesLambda:
    Description: The ARN of the created MarketdataDownloaderCleanTestFilesLambda function
    Value:
      !GetAtt MarketdataDownloaderCleanTestFilesLambda.Arn
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MarketdataDownloaderCleanTestFilesLambda ] ]

  MarketdataDownloaderCleanTestFilesLambdaName:
    Description: The Name of the created MarketdataDownloaderCleanTestFilesLambda function
    Value:
      'market-data-downloader-clean-test-files'
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MarketdataDownloaderCleanTestFilesLambdaName ] ]
