version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r market-data-downloader-create-bucket/requirements.txt -t market-data-downloader-create-bucket

artifacts:
  base-directory: market-data-downloader-create-bucket
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
